INSERT INTO burgers (burger_name) VALUES ('Double Cheeseburger');
INSERT INTO burgers (burger_name) VALUES ('Cheeseburger');
INSERT INTO burgers (burger_name) VALUES ('Triple Cheeseburger');
INSERT INTO burgers (burger_name) VALUES ('Impossible Burger');
INSERT INTO burgers (burger_name) VALUES ('Bison Burger');
INSERT INTO burgers (burger_name) VALUES ('Avocado Bacon Burger');
INSERT INTO burgers (burger_name) VALUES ('Swiss Cheese Burger');
INSERT INTO burgers (burger_name) VALUES ('Juicy Lucy');
INSERT INTO burgers (burger_name) VALUES ('Hot and Spicy PepperJack');
INSERT INTO burgers (burger_name) VALUES ('Hamburger');